import { useEffect, useRef, useState } from "react";
import { useRpc, useWorkspace, type PluginWorkspacePanelProps } from "@getpaseo/plugin";
import { cancelShipGateRpc, runShipGateRpc } from "./rpc";

export function ShipGatePanel({ theme, workspaceId }: PluginWorkspacePanelProps) {
  const run = useRpc(runShipGateRpc); const cancel = useRpc(cancelShipGateRpc); const generation = useRef(0); const token = useRef(""); const [state, setState] = useState<{ text: string; error?: string; inFlight: boolean }>({ text: "Ready", inFlight: false }); const directory = useWorkspace(workspaceId, (workspace) => workspace.directory) ?? "";
  useEffect(() => { const oldToken = token.current; const oldGeneration = generation.current; if (oldToken) void cancel({ generation: oldGeneration, runToken: oldToken, workspaceId }).catch(() => undefined); generation.current += 1; token.current = ""; setState({ text: directory ? "Ready" : "Workspace unavailable", inFlight: false }); return () => { if (oldToken) void cancel({ generation: oldGeneration, runToken: oldToken, workspaceId }).catch(() => undefined); }; }, [workspaceId, directory]);
  const start = () => { const requestGeneration = ++generation.current; const runToken = `${Date.now()}-${Math.random().toString(36).slice(2)}-${Math.random().toString(36).slice(2)}`; token.current = runToken; setState({ text: "Running…", inFlight: true }); void run({ generation: requestGeneration, runToken, workspaceId, policy: { commandIds: ["git-status"], requiredFiles: [] } }).then((result) => { if (result.generation === generation.current && token.current === runToken) { token.current = ""; setState({ text: JSON.stringify(result.report, null, 2), inFlight: false }); } }).catch((error: unknown) => { if (requestGeneration === generation.current && token.current === runToken) { token.current = ""; setState({ text: "", error: error instanceof Error ? error.message : String(error), inFlight: false }); } }); };
  const stop = () => { const requestGeneration = generation.current; const runToken = token.current; void cancel({ generation: requestGeneration, runToken, workspaceId }).then(() => { if (generation.current === requestGeneration && token.current === runToken) setState((current) => ({ ...current, text: "Cancellation requested", inFlight: true })); }).catch((error: unknown) => { if (generation.current === requestGeneration && token.current === runToken) setState({ text: "", error: error instanceof Error ? error.message : String(error), inFlight: true }); }); };
  return <div style={{ color: theme.colors.foreground, padding: 16 }}><h2>Ship Gate</h2><button disabled={!directory || state.inFlight} onClick={start}>Run readiness checks</button><button disabled={!state.inFlight} onClick={stop}>Stop</button><pre style={{ whiteSpace: "pre-wrap" }}>{state.error ? `Error: ${state.error}` : state.text}</pre></div>;
}
