import { defineRpc } from "@getpaseo/plugin/server";
import { z } from "zod";

const token = z.string().min(16).max(256);
const workspace = z.string().min(1).max(256);
const policy = z.object({ commandIds: z.array(z.enum(["git-status"])).max(8).transform((ids) => [...new Set(ids)]).default([]), requiredFiles: z.array(z.string().min(1).max(512)).max(128).transform((files) => [...new Set(files)]).refine((files) => files.reduce((n, file) => n + file.length, 0) <= 16_384, "requiredFiles request too large").default([]) }).default({ commandIds: [], requiredFiles: [] });
const result = z.object({ id: z.string().max(256), title: z.string().max(512), status: z.enum(["passed", "failed", "skipped", "unavailable", "error"]), evidence: z.string().max(16_000), durationMs: z.number().finite().nonnegative().max(3_600_000), collectedAt: z.string().max(128), freshness: z.enum(["fresh", "stale"]), outcome: z.enum(["complete", "partial", "timeout", "cancelled", "malformed-listing", "operational-error"]), truncated: z.boolean(), incomplete: z.boolean(), errorKind: z.string().max(128).optional(), detail: z.string().max(2048).optional() });
export const runShipGateRpc = defineRpc({ name: "ship-gate.run", input: z.object({ generation: z.number().int().nonnegative(), runToken: token, workspaceId: workspace, policy }), output: z.object({ generation: z.number().int().nonnegative(), report: z.object({ workspace: z.string().max(4096), collectedAt: z.string().max(128), generatedText: z.string().max(16_000), generatedTextTruncated: z.boolean(), results: z.array(result).max(256) }) }).refine((value) => JSON.stringify(value).length <= 1_000_000, "response too large") });
export const cancelShipGateRpc = defineRpc({ name: "ship-gate.cancel", input: z.object({ generation: z.number().int().nonnegative(), runToken: token, workspaceId: workspace }), output: z.object({ cancelled: z.boolean() }) });
