import { describe, expect, it } from "vitest";
import { mkdir, mkdtemp, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { BUILTIN_COMMANDS, defaultRunner, runShipGate, type ProcessRunner } from "./ship-gate";

const fake = (responses: Record<string, { stdout?: string; stderr?: string; exitCode?: number }>, calls: string[] = []): ProcessRunner => async (exe, args, options) => { calls.push(`${exe} ${args.join(" ")} ${options.timeoutMs}`); const r = responses[args.slice(2).join(" ")] ?? {}; return { stdout: r.stdout ?? "", stderr: r.stderr ?? "", exitCode: r.exitCode ?? 0 }; };
async function repo() { const root = await mkdtemp(path.join(os.tmpdir(), "ship-gate-")); await mkdir(path.join(root, ".git")); return root; }
const base = { "rev-parse --show-toplevel": { stdout: "ROOT" }, "status --porcelain=v1": {}, "diff --name-only --diff-filter=U": {}, "symbolic-ref --quiet --short HEAD": { stdout: "main" }, "show -s --format=%H%n%an <%ae>": { stdout: "abc\nA <a@b>" }, "rev-list --left-right --count HEAD...@{upstream}": { stdout: "0\t1" }, "grep -n -I -e ^<<<<<<<  -e ^======= -e ^>>>>>>> ": { exitCode: 1 } };
describe("ship gate", () => {
  it("requires the selected directory to be the Git root and honors the policy timeout", async () => { const root = await repo(); const calls: string[] = []; await expect(runShipGate(root, { timeoutMs: 1234 }, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root } }, calls) })).resolves.toBeTruthy(); expect(calls.every((c) => c.endsWith("1234"))).toBe(true); await expect(runShipGate(root, {}, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: path.dirname(root) } }) })).rejects.toThrow(/selected Git repository root/); });
  it("maps conflict grep 1 to passed, Git errors to error, and nonzero commands to failed", async () => { const root = await repo(); const report = await runShipGate(root, { allowedCommands: { "trusted-test": { executable: "trusted-test", args: [] } }, commands: [{ id: "trusted-test", title: "Tests", executable: "trusted-test", args: [] }] }, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root }, "status --porcelain=v1": { exitCode: 2, stderr: "bad git" }, "grep -n -I -e ^<<<<<<<  -e ^======= -e ^>>>>>>> ": { exitCode: 1 }, "": { exitCode: 3, stderr: "failed tests" } }) }); expect(report.results.find((r) => r.id === "static-conflict-markers")?.status).toBe("passed"); expect(report.results.find((r) => r.id === "git-dirty")?.status).toBe("error"); expect(report.results.find((r) => r.id === "trusted-test")?.status).toBe("failed"); });
  it("rejects arbitrary commands, Git/path bypasses, malformed values, directories, and escaping symlinks", async () => { const root = await repo(); await mkdir(path.join(root, "dir")); const outside = await mkdtemp(path.join(os.tmpdir(), "outside-")); let hasLink = true; try { await symlink(outside, path.join(root, "link")); } catch { hasLink = false; } const opts = { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root } }) }; const command = (executable: string, args: string[]) => ({ allowedCommands: { x: { executable, args } }, commands: [{ id: "x", title: "X", executable, args }] }); await expect(runShipGate(root, command("rm", []), opts)).rejects.toThrow(/not allowed|exactly authorized|allowlist/); await expect(runShipGate(root, command("git", ["-C", "..", "push"]), opts)).rejects.toThrow(/not allowed|workspace/); await expect(runShipGate(root, { maxEvidenceBytes: -1 }, opts)).rejects.toThrow(/non-negative/); await expect(runShipGate(root, { requiredFiles: ["missing.txt"] }, opts)).resolves.toMatchObject({ results: expect.arrayContaining([expect.objectContaining({ id: "required-file:missing.txt", status: "failed" })]) }); await expect(runShipGate(root, { requiredFiles: ["dir"] }, opts)).resolves.toMatchObject({ results: expect.arrayContaining([expect.objectContaining({ id: "required-file:dir", status: "failed" })]) }); if (hasLink) await expect(runShipGate(root, { requiredFiles: ["link"] }, opts)).resolves.toMatchObject({ results: expect.arrayContaining([expect.objectContaining({ id: "required-file:link", status: "error" })]) }); });
  it("bounds UTF-8 evidence exactly, including tiny limits, and stops promptly on cancellation", async () => { const root = await repo(); for (const limit of [0, 1, 2, 3, 4]) { const report = await runShipGate(root, { maxEvidenceBytes: limit }, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root }, "status --porcelain=v1": { stdout: "😀😀" } }) }); expect(report.results.every((r) => Buffer.byteLength(r.evidence) <= limit)).toBe(true); } const controller = new AbortController(); controller.abort(); const cancelled: ProcessRunner = async (_e, _a, options) => { if (options.signal?.aborted) throw Object.assign(new Error("aborted"), { kind: "cancelled" }); return { stdout: "", stderr: "", exitCode: 0 }; }; await expect(runShipGate(root, {}, { signal: controller.signal, runner: cancelled })).rejects.toThrow("aborted"); });
  it("normalizes a real execFile nonzero exit and rejects prototype allowlist authorization", async () => { const root = await repo(); const r = await defaultRunner(process.execPath, ["-e", "process.stderr.write('no'); process.exit(7)"], { cwd: root, timeoutMs: 1000, maxBytes: 1000 }); expect(r).toMatchObject({ kind: "exit", exitCode: 7, stderr: "no" }); const inherited = Object.create({ test: "trusted-test" }); await expect(runShipGate(root, { allowedCommands: inherited, commands: [{ id: "test", title: "Test", executable: "trusted-test", args: [] }] }, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root } }) })).rejects.toThrow(/plain record/); });
  it("scans ignored and untracked marker files without leaving the workspace", async () => { const root = await repo(); await writeFile(path.join(root, "untracked.txt"), "<<<<<<< ours\ncontent\n"); const report = await runShipGate(root, {}, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root }, "ls-files --others --ignored --exclude-standard -z": { stdout: "untracked.txt\0" } }) }); expect(report.results.find((r) => r.id === "static-conflict-markers")?.status).toBe("failed"); expect(await import("node:fs/promises").then((fs) => fs.readFile(path.join(root, "untracked.txt"), "utf8"))).toContain("<<<<<<<"); });
  it("distinguishes no upstream from real sync errors and returns structured scan cancellation", async () => { const root = await repo(); const noUpstream = await runShipGate(root, {}, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root }, "rev-list --left-right --count HEAD...@{upstream}": { exitCode: 128, stderr: "no upstream configured" } }) }); expect(noUpstream.results.find((r) => r.id === "git-sync")?.status).toBe("unavailable"); const broken = await runShipGate(root, {}, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root }, "rev-list --left-right --count HEAD...@{upstream}": { exitCode: 128, stderr: "authentication failed" } }) }); expect(broken.results.find((r) => r.id === "git-sync")?.status).toBe("error"); const controller = new AbortController(); const cancelling: ProcessRunner = async (e, a, o) => { const r = fake({ ...base, "rev-parse --show-toplevel": { stdout: root } }); const result = await r(e, a, o); if (a.includes("grep")) controller.abort(); return result; }; const cancelled = await runShipGate(root, {}, { signal: controller.signal, runner: cancelling }); expect(cancelled.results.some((r) => r.outcome === "cancelled")).toBe(true); });
  it("normalizes Windows Git executable names and rejects compact config bypasses", async () => { const root = await repo(); const opts = { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root } }) }; for (const executable of ["git.exe", "git.cmd"]) await expect(runShipGate(root, { allowedCommands: { x: { executable, args: ["-cfoo=bar"] } }, commands: [{ id: "x", title: "x", executable, args: ["-cfoo=bar"] }] }, opts)).rejects.toThrow(/Git config|redirection/); });
  it("rejects malformed successful sync counts", async () => { const root = await repo(); for (const stdout of ["", "NaN 0", "0", "0 1 2"]) { const report = await runShipGate(root, {}, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root }, "rev-list --left-right --count HEAD...@{upstream}": { stdout } }) }); expect(report.results.find((r) => r.id === "git-sync")?.status).toBe("error"); } });
  it("executes the fixed built-in read-only command and rejects unsupported IDs", async () => { const root = process.cwd(); const calls: string[] = []; const report = await runShipGate(root, { commands: [{ id: "git-status", title: "Git status", executable: BUILTIN_COMMANDS["git-status"].executable, args: [...BUILTIN_COMMANDS["git-status"].args] }] }, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root } }, calls) }); expect(report.results.some((r) => r.id === "git-status")).toBe(true); await expect(runShipGate(root, { commands: [{ id: "unknown", title: "Unknown", executable: "git", args: [] }] }, { runner: fake({ ...base, "rev-parse --show-toplevel": { stdout: root } }) })).rejects.toThrow(/built-in|authorized/); });
});
