import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { promisify } from "node:util";

const exec = promisify(execFile);
export const MAX_EVIDENCE_BYTES = 16_000;
export const DEFAULT_TIMEOUT_MS = 30_000;
export const MAX_TIMEOUT_MS = 10 * 60_000;
export const MAX_SCAN_FILES = 2_000;
export const MAX_SCAN_BYTES = 4 * 1024 * 1024;
const PROCESS_OUTPUT_BYTES = 256 * 1024;
const sanitizedGitEnv = (): NodeJS.ProcessEnv => { const clean = Object.fromEntries(Object.entries(process.env).filter(([key]) => !key.toUpperCase().startsWith("GIT_"))); return { ...clean, GIT_CONFIG_NOSYSTEM: "1", GIT_CONFIG_GLOBAL: process.platform === "win32" ? "NUL" : "/dev/null", GIT_CONFIG_SYSTEM: process.platform === "win32" ? "NUL" : "/dev/null", GIT_OPTIONAL_LOCKS: "0", GIT_TERMINAL_PROMPT: "0", GIT_ATTR_NOSYSTEM: "1", GIT_FSmonitor: "false", GIT_INDEX_FILE: undefined, GIT_EXTERNAL_DIFF: undefined, GIT_DIFF_OPTS: undefined, GIT_PAGER: "cat", GIT_EDITOR: ":", GIT_SEQUENCE_EDITOR: ":", GIT_ASKPASS: ":" }; };
export type CheckStatus = "passed" | "failed" | "skipped" | "unavailable" | "error";
export type ScanOutcome = "complete" | "partial" | "timeout" | "cancelled" | "malformed-listing" | "operational-error";
export interface CheckResult { readonly id: string; readonly title: string; readonly status: CheckStatus; readonly evidence: string; readonly durationMs: number; readonly collectedAt: string; readonly freshness: "fresh" | "stale"; readonly outcome: ScanOutcome; readonly truncated: boolean; readonly incomplete: boolean; readonly errorKind?: string; readonly detail?: string; }
export interface CheckReport { readonly workspace: string; readonly collectedAt: string; readonly results: readonly CheckResult[]; readonly generatedText: string; readonly generatedTextTruncated: boolean; }
export interface CommandCheck { readonly id: string; readonly title: string; readonly executable: string; readonly args: readonly string[]; readonly timeoutMs?: number; readonly maxEvidenceBytes?: number; }
export interface AuthorizedCommand { readonly executable: string; readonly args: readonly string[] }
export interface CheckPolicy { readonly requiredFiles?: readonly string[]; readonly commands?: readonly CommandCheck[]; readonly conflictMarkers?: boolean; readonly maxEvidenceBytes?: number; readonly timeoutMs?: number; readonly allowedCommands?: Readonly<Record<string, AuthorizedCommand>>; }
export interface ProcessResult { stdout: string; stderr: string; exitCode: number; kind?: "exit" | "partial" }
export interface ProcessRunner { (executable: string, args: readonly string[], options: { cwd: string; timeoutMs: number; maxBytes: number; signal?: AbortSignal; env?: NodeJS.ProcessEnv }): Promise<ProcessResult> }
type RunFailure = Error & { kind?: "launch" | "timeout" | "cancelled" | "missing" | "listing" | "operational"; exitCode?: number; stdout?: string; stderr?: string };

export const defaultRunner: ProcessRunner = async (executable, args, options) => {
  try { const actual = executable === "git" ? await canonicalGitExecutable() : executable; const r = await exec(actual, [...args], { cwd: options.cwd, env: options.env, timeout: options.timeoutMs, maxBuffer: options.maxBytes, signal: options.signal }); return { stdout: String(r.stdout), stderr: String(r.stderr), exitCode: 0 }; }
  catch (error) { const e = error as RunFailure & { killed?: boolean; code?: string | number; stdout?: string; stderr?: string; message?: string }; if (options.signal?.aborted || e.name === "AbortError") e.kind = "cancelled"; else if (e.code === "ETIMEDOUT" || e.killed) e.kind = "timeout"; else if (e.code === "ERR_CHILD_PROCESS_STDIO_MAXBUFFER" || e.message?.includes("maxBuffer")) return { kind: "partial", exitCode: 1, stdout: String(e.stdout ?? ""), stderr: String(e.stderr ?? "") }; else if (typeof e.code === "number") { return { kind: "exit", exitCode: e.code, stdout: String(e.stdout ?? ""), stderr: String(e.stderr ?? "") }; } else if (e.code === "ENOENT") e.kind = "missing"; else if (typeof e.code === "string") e.kind = "launch"; throw e; }
};
let canonicalGitPromise: Promise<string> | undefined;
async function canonicalGitExecutable(): Promise<string> { if (!canonicalGitPromise) canonicalGitPromise = (async () => { const lookup = process.platform === "win32" ? await exec("where", ["git.exe"], { maxBuffer: 4096 }) : await exec("which", ["git"], { maxBuffer: 4096 }); const candidate = String(lookup.stdout).split(/\r?\n/).find(Boolean)?.trim(); if (!candidate || !path.isAbsolute(candidate)) throw Object.assign(new Error("canonical Git executable unavailable"), { kind: "missing" }); return fs.realpath(candidate); })(); return canonicalGitPromise; }
function bounded(text: string, limit: number): string { if (limit <= 0 || text.length === 0) return ""; const bytes = Buffer.from(text, "utf8"); if (bytes.byteLength <= limit) return text; const suffix = limit >= 3 ? "…" : ""; let end = Math.max(0, limit - Buffer.byteLength(suffix)); while (end > 0 && (bytes[end] & 0xc0) === 0x80) end--; return `${bytes.subarray(0, end).toString("utf8")}${suffix}`; }
const makeResult = (id: string, title: string, status: CheckStatus, evidence: string, started: number, at: string, limit: number, detail?: string, outcome?: ScanOutcome): CheckResult => { const wasTruncated = Buffer.byteLength(evidence, "utf8") > limit; const resolved = outcome ?? (wasTruncated || evidence.includes("scan truncated") ? "partial" : "complete"); return Object.freeze({ id, title, status, evidence: bounded(evidence, limit), durationMs: Math.max(0, Date.now() - started), collectedAt: at, freshness: "fresh", outcome: resolved, truncated: wasTruncated || resolved === "partial", incomplete: resolved !== "complete", ...(detail ? { detail } : {}), ...(resolved !== "complete" ? { errorKind: resolved } : {}) }); };
/** Fixed, read-only commands exposed to policy authors. Their executable and args are not configurable. */
export const BUILTIN_COMMANDS: Readonly<Record<string, AuthorizedCommand>> = {
  "git-status": { executable: "git", args: ["status", "--short"] },
};
const INTERNAL_COMMANDS: Readonly<Record<string, AuthorizedCommand>> = { ...BUILTIN_COMMANDS, "trusted-test": { executable: "trusted-test", args: [] } };
const executableName = (value: string) => path.basename(value).toLowerCase().replace(/\.(?:exe|cmd|bat)$/i, "");
const isGitExecutable = (value: string) => executableName(value) === "git";
const mutatingGit = new Set(["add", "am", "apply", "branch", "checkout", "cherry-pick", "clean", "clone", "commit", "fetch", "gc", "init", "merge", "mv", "pull", "push", "rebase", "revert", "reset", "restore", "rm", "stash", "tag", "update-ref"]);
const validText = (value: unknown, label: string) => { if (typeof value !== "string" || value.length === 0 || value.length > 200) throw new Error(`${label} must be a non-empty bounded string`); return value; };
const validPositive = (value: unknown, label: string, max: number) => { if (typeof value !== "number" || !Number.isFinite(value) || value <= 0 || value > max) throw new Error(`${label} must be finite, positive, and <= ${max}`); return value; };
function validatePolicy(policy: CheckPolicy): Required<Pick<CheckPolicy, "requiredFiles" | "commands" | "conflictMarkers" | "maxEvidenceBytes" | "timeoutMs">> {
  if (!policy || typeof policy !== "object" || Array.isArray(policy)) throw new Error("policy must be an object");
  const maxEvidenceBytes = policy.maxEvidenceBytes === undefined ? MAX_EVIDENCE_BYTES : (typeof policy.maxEvidenceBytes === "number" && Number.isFinite(policy.maxEvidenceBytes) && policy.maxEvidenceBytes >= 0 && policy.maxEvidenceBytes <= MAX_EVIDENCE_BYTES ? policy.maxEvidenceBytes : (() => { throw new Error("maxEvidenceBytes must be finite, non-negative, and bounded"); })());
  const timeoutMs = policy.timeoutMs === undefined ? DEFAULT_TIMEOUT_MS : validPositive(policy.timeoutMs, "timeoutMs", MAX_TIMEOUT_MS);
  const requiredFiles = policy.requiredFiles ?? []; if (!Array.isArray(requiredFiles) || requiredFiles.some((p) => typeof p !== "string" || p.length === 0 || path.isAbsolute(p) || p.split(/[\\/]/).some((part) => part === ".."))) throw new Error("requiredFiles must contain relative, non-traversing paths");
  if (policy.allowedCommands !== undefined && (typeof policy.allowedCommands !== "object" || policy.allowedCommands === null || ![null, Object.prototype].includes(Object.getPrototypeOf(policy.allowedCommands)))) throw new Error("allowedCommands must be a plain record");
  const commands = policy.commands ?? []; if (!Array.isArray(commands)) throw new Error("commands must be an array");
  for (const c of commands) { const fixed = INTERNAL_COMMANDS[c.id]; if (fixed && policy.allowedCommands && Object.hasOwn(policy.allowedCommands, c.id) && (policy.allowedCommands[c.id].executable !== fixed.executable || JSON.stringify(policy.allowedCommands[c.id].args) !== JSON.stringify(fixed.args))) throw new Error("built-in command specs cannot be overridden"); }
  if (commands.some((c) => Array.isArray(c.args) && c.args.some((a: string) => a.split(/[\\/]/).includes("..")))) throw new Error("command paths must not contain traversal components or leave workspace");
  for (const c of commands) { if (executableName(c.executable) !== "git") continue; const gitOptions = /^(?:-c.*|--config(?:=|$)|--config-env(?:=|$)|-C.*|--git-dir(?:=|$)|--work-tree(?:=|$)|--exec-path(?:=|$)|--namespace(?:=|$))/i; if (c.args.some((a: string) => gitOptions.test(a))) throw new Error("Git config or repository redirection is not allowed"); }
  for (const c of commands) { if (!isGitExecutable(c.executable)) continue; if (c.args.some((a: string) => mutatingGit.has(a.replace(/^--?/, "")))) throw new Error("Git mutation is not allowed"); }
  const forbidden = new Set(["sh", "bash", "zsh", "cmd", "cmd.exe", "powershell", "powershell.exe", "pwsh", "node", "node.exe", "python", "python.exe", "rm", "rm.exe", "del", "erase"]);
  const mutatingGitLocal = mutatingGit;
  if (commands.some((c) => !Object.hasOwn(INTERNAL_COMMANDS, c.id))) throw new Error("only fixed built-in read-only command IDs are allowed; command is not exactly authorized");
  for (const c of commands) { validText(c.id, "command id"); validText(c.title, "command title"); validText(c.executable, "command executable"); if (!Array.isArray(c.args) || c.args.some((a: unknown) => typeof a !== "string" || a.includes("\0"))) throw new Error("command args must be strings"); if (forbidden.has(path.basename(c.executable).toLowerCase())) throw new Error("shell, interpreter, and mutating executables are not allowed"); const gitBad = /^(?:-c|--config|--config-env|-C.+|--git-dir(?:=|$)|--work-tree(?:=|$)|--exec-path(?:=|$)|--namespace(?:=|$)|--literal-pathspecs|--glob|--noglob)$/i; if (path.basename(c.executable).toLowerCase() === "git" && (c.args.some((a: string) => gitBad.test(a)) || c.args.some((a: string) => mutatingGit.has(a.replace(/^--?/, ""))))) throw new Error("mutating or repository-redirection Git arguments are not allowed"); if (c.args.some((a: string) => path.isAbsolute(a) || a === ".." || a.startsWith(`..${path.sep}`) || a.startsWith("../"))) throw new Error("command paths must stay within the selected workspace"); if (c.timeoutMs !== undefined) validPositive(c.timeoutMs, "command timeoutMs", timeoutMs); if (c.maxEvidenceBytes !== undefined && (typeof c.maxEvidenceBytes !== "number" || !Number.isFinite(c.maxEvidenceBytes) || c.maxEvidenceBytes < 0 || c.maxEvidenceBytes > maxEvidenceBytes)) throw new Error("command maxEvidenceBytes must be finite, non-negative, and bounded"); const allowed = policy.allowedCommands; const spec = allowed && Object.hasOwn(allowed, c.id) ? allowed[c.id] : INTERNAL_COMMANDS[c.id]; if (!spec || spec.executable !== c.executable || JSON.stringify(spec.args) !== JSON.stringify(c.args)) throw new Error(`command ${c.id} is not exactly authorized`); }
  return Object.freeze({ requiredFiles: Object.freeze([...requiredFiles]), commands: Object.freeze(commands.map((c) => Object.freeze({ ...c, args: Object.freeze([...c.args]) }))), conflictMarkers: policy.conflictMarkers !== false, maxEvidenceBytes, timeoutMs });
}
async function workspaceRoot(directory: string, runner: ProcessRunner, timeoutMs: number, signal?: AbortSignal): Promise<string> {
  if (!directory || !path.isAbsolute(directory)) throw new Error("workspace must be an absolute directory"); const root = await fs.realpath(directory); if (!(await fs.stat(root)).isDirectory()) throw new Error("workspace must be a directory");
  let r: ProcessResult; try { r = await invoke(root, ["rev-parse", "--show-toplevel"], runner, timeoutMs, 4096, signal); } catch (error) { if (signal?.aborted || (error as RunFailure).kind === "cancelled") throw Object.assign(new Error("aborted"), { kind: "cancelled" }); throw error; } if (r.exitCode !== 0) throw new Error("workspace is not a Git repository"); const gitRoot = await fs.realpath(r.stdout.trim()); if (gitRoot !== root) throw new Error("workspace must be the selected Git repository root"); return root;
}
function failureResult(error: unknown, started: number, id: string, title: string, at: string, limit: number): CheckResult { const e = error as RunFailure; const kind = e.kind ?? "launch"; const status: CheckStatus = kind === "cancelled" ? "skipped" : kind === "timeout" ? "error" : kind === "listing" ? "error" : kind === "launch" || kind === "missing" || kind === "operational" ? "unavailable" : "error"; const outcome: ScanOutcome = kind === "cancelled" ? "cancelled" : kind === "timeout" ? "timeout" : kind === "listing" ? "malformed-listing" : kind === "operational" ? "partial" : "operational-error"; return makeResult(id, title, status, `${kind}: ${e.message ?? String(error)}${e.exitCode === undefined ? "" : ` (exit code ${e.exitCode})`}`, started, at, limit, kind, outcome); }
async function invoke(root: string, args: string[], runner: ProcessRunner, timeoutMs: number, limit: number, signal?: AbortSignal) { return runner("git", ["-C", root, ...args], { cwd: root, timeoutMs, maxBytes: Math.max(4096, Math.min(PROCESS_OUTPUT_BYTES, limit || PROCESS_OUTPUT_BYTES)), signal, env: sanitizedGitEnv() }); }
async function untrackedMarkers(root: string, timeoutMs: number, limit: number, signal?: AbortSignal): Promise<string> {
  const started = Date.now(); let files = 0; let bytes = 0; const hits: string[] = []; const queue = [root];
  while (queue.length && files < MAX_SCAN_FILES && bytes < MAX_SCAN_BYTES) {
    if (signal?.aborted) throw Object.assign(new Error("aborted"), { kind: "cancelled" }); if (Date.now() - started > timeoutMs) throw Object.assign(new Error("scan timeout"), { kind: "timeout" });
    const directory = queue.shift()!; let entries: import("node:fs").Dirent[]; try { entries = await fs.readdir(directory, { withFileTypes: true }); } catch { continue; }
    for (const entry of entries) { if (signal?.aborted) throw Object.assign(new Error("aborted"), { kind: "cancelled" }); if (Date.now() - started > timeoutMs) throw Object.assign(new Error("scan timeout"), { kind: "timeout" }); const relative = path.relative(root, path.join(directory, entry.name)); if (relative.split(/[\\/]/).some((part) => /^(\.git|node_modules|dist|build|generated|coverage)$/i.test(part) || /(secret|token|password|credential|apikey)/i.test(part))) continue; const candidate = path.join(directory, entry.name); if (entry.isDirectory()) { queue.push(candidate); continue; } if (!entry.isFile()) continue; files++; try { const handle = await fs.open(candidate, "r"); try { const buffer = Buffer.alloc(Math.min(64 * 1024, MAX_SCAN_BYTES - bytes)); const read = await handle.read(buffer, 0, buffer.length, 0); bytes += read.bytesRead; if (/^(<<<<<<< |=======|>>>>>>> )/m.test(buffer.subarray(0, read.bytesRead).toString("utf8"))) hits.push(relative); } finally { await handle.close(); } } catch { /* inaccessible files are skipped from advisory evidence */ } if (Buffer.byteLength(hits.join("\n"), "utf8") >= limit) return bounded(hits.join("\n"), limit); }
  }
  return hits.join("\n");
}
async function gitUntrackedMarkers(root: string, runner: ProcessRunner, timeoutMs: number, limit: number, signal?: AbortSignal): Promise<{ text: string; truncated: boolean }> {
  if (signal?.aborted) throw Object.assign(new Error("aborted"), { kind: "cancelled" });
  const listing = await invoke(root, ["ls-files", "--others", "--ignored", "--exclude-standard", "-z"], runner, timeoutMs, limit, signal); if (listing.kind === "partial") return { text: bounded(listing.stdout, limit), truncated: true }; if (listing.exitCode !== 0) throw Object.assign(new Error(listing.stderr || `exit code ${listing.exitCode}`), { kind: "listing", exitCode: listing.exitCode }); if (listing.stdout.length > 0 && !listing.stdout.endsWith("\0")) throw Object.assign(new Error("malformed or truncated Git file listing"), { kind: "listing" });
  const started = Date.now(); let count = 0; let total = 0; const hits: string[] = [];
  for (const relative of listing.stdout.split("\0").filter(Boolean)) { if (signal?.aborted) throw Object.assign(new Error("aborted"), { kind: "cancelled" }); if (Date.now() - started > timeoutMs || count++ >= MAX_SCAN_FILES || total >= MAX_SCAN_BYTES) throw Object.assign(new Error("scan timeout or limit"), { kind: "timeout" }); if (relative.split(/[\\/]/).some((part) => /^(\.git|node_modules|dist|build|generated|coverage)$/i.test(part) || /(secret|token|password|credential|apikey)/i.test(part))) continue; const candidate = path.resolve(root, relative); const rel = path.relative(root, candidate); if (rel.startsWith(`..${path.sep}`) || path.isAbsolute(rel)) continue; try { const target = await fs.realpath(candidate); const targetRel = path.relative(root, target); if (targetRel.startsWith(`..${path.sep}`) || path.isAbsolute(targetRel)) throw Object.assign(new Error("untracked file escapes workspace"), { kind: "operational" }); const handle = await fs.open(target, "r"); try { const buffer = Buffer.alloc(Math.min(64 * 1024, MAX_SCAN_BYTES - total)); const read = await handle.read(buffer, 0, buffer.length, 0); total += read.bytesRead; if (/^(<<<<<<< |=======|>>>>>>> )/m.test(buffer.subarray(0, read.bytesRead).toString("utf8"))) hits.push(relative); } finally { await handle.close(); } } catch (error) { if ((error as RunFailure).kind) throw error; throw Object.assign(new Error(`unable to read untracked file ${relative}: ${error instanceof Error ? error.message : String(error)}`), { kind: "operational" }); } if (Buffer.byteLength(hits.join("\n"), "utf8") >= limit) break; }
  return { text: bounded(hits.join("\n"), limit), truncated: Buffer.byteLength(hits.join("\n"), "utf8") > limit || listing.stdout.split("\0").filter(Boolean).length > MAX_SCAN_FILES || total >= MAX_SCAN_BYTES };
}
async function gitChecks(root: string, at: string, runner: ProcessRunner, policy: ReturnType<typeof validatePolicy>, signal?: AbortSignal): Promise<CheckResult[]> {
  const checks: CheckResult[] = []; const run = async (id: string, title: string, args: string[], map: (r: { stdout: string; stderr: string; exitCode: number }) => [CheckStatus, string]) => { if (signal?.aborted) return; const started = Date.now(); try { const r = await invoke(root, args, runner, policy.timeoutMs, policy.maxEvidenceBytes, signal); const mapped = map(r); checks.push(makeResult(id, title, mapped[0], `${mapped[1]}${r.kind === "partial" ? "\noutput truncated: partial evidence" : ""}`, started, at, policy.maxEvidenceBytes, undefined, r.kind === "partial" ? "partial" : undefined)); } catch (e) { checks.push(failureResult(e, started, id, title, at, policy.maxEvidenceBytes)); } };
  await run("git-dirty", "Working tree", ["status", "--porcelain=v1"], (r) => [r.exitCode === 0 ? (r.stdout.trim() ? "failed" : "passed") : "error", r.stdout || r.stderr || "clean"]);
  await run("git-conflicts", "Unresolved conflicts", ["diff", "--name-only", "--diff-filter=U"], (r) => [r.exitCode === 0 ? (r.stdout.trim() ? "failed" : "passed") : "error", r.stdout || r.stderr || "none"]);
  await run("git-head", "HEAD state", ["symbolic-ref", "--quiet", "--short", "HEAD"], (r) => [r.exitCode === 0 ? "passed" : r.exitCode === 1 ? "failed" : "error", r.exitCode === 0 ? `branch: ${r.stdout.trim()}` : r.exitCode === 1 ? "detached HEAD" : r.stderr || `exit code ${r.exitCode}`]);
  await run("git-identity", "Commit identity", ["show", "-s", "--format=%H%n%an <%ae>"], (r) => [r.exitCode === 0 ? "passed" : "error", r.stdout || r.stderr || `exit code ${r.exitCode}`]);
  await run("git-sync", "Ahead or behind", ["rev-list", "--left-right", "--count", "HEAD...@{upstream}"], (r) => { if (r.exitCode !== 0) return [/no upstream|no tracking information|upstream is gone/i.test(r.stderr) ? "unavailable" : "error", r.stdout || r.stderr || "no upstream configured"]; const tokens = r.stdout.trim().split(/\s+/); if (tokens.length !== 2 || tokens.some((token) => !/^\d+$/.test(token))) return ["error", r.stdout || "malformed ahead/behind output"]; const [ahead, behind] = tokens.map(Number); return [ahead === 0 && behind === 0 ? "passed" : "failed", `ahead: ${ahead}; behind: ${behind}`]; });
  return checks;
}
export async function runShipGate(directory: string, input: CheckPolicy = {}, options: { signal?: AbortSignal; runner?: ProcessRunner; now?: () => Date } = {}): Promise<CheckReport> {
  if (options.signal?.aborted) { const at = (options.now ?? (() => new Date()))().toISOString(); const check = makeResult("run", "Ship Gate run", "skipped", "cancelled", Date.now(), at, input.maxEvidenceBytes ?? MAX_EVIDENCE_BYTES, "cancelled", "cancelled"); return Object.freeze({ workspace: directory, collectedAt: at, results: Object.freeze([check]), generatedText: "Ship Gate run cancelled", generatedTextTruncated: false }); }
  if (!options.runner && input.commands?.some((c) => c.id === "trusted-test")) throw new Error("test-only command runner cannot execute in production");
  const policy = validatePolicy(input); const runner = options.runner ?? defaultRunner; const root = await workspaceRoot(directory, runner, policy.timeoutMs, options.signal); for (const c of policy.commands) { if (INTERNAL_COMMANDS[c.id]) continue; if (!path.isAbsolute(c.executable)) throw new Error("external command executable must be absolute"); const actual = await fs.realpath(c.executable); const authorized = await fs.realpath(input.allowedCommands![c.id].executable); if (actual !== authorized) throw new Error("command executable does not match canonical trusted path"); } const at = (options.now ?? (() => new Date()))().toISOString(); const results = await gitChecks(root, at, runner, policy, options.signal);
  const add = async (id: string, title: string, fn: () => Promise<[CheckStatus, string]>, limit = policy.maxEvidenceBytes) => { if (options.signal?.aborted) return; const started = Date.now(); try { const [s, e] = await fn(); results.push(makeResult(id, title, s, e, started, at, limit)); } catch (e) { results.push(failureResult(e, started, id, title, at, limit)); } };
  if (policy.conflictMarkers) await add("static-conflict-markers", "Conflict markers", async () => { const r = await invoke(root, ["grep", "-n", "-I", "-e", "^<<<<<<< ", "-e", "^=======", "-e", "^>>>>>>> "], runner, policy.timeoutMs, policy.maxEvidenceBytes, options.signal); if (r.exitCode !== 0 && r.exitCode !== 1) return ["error", r.stderr || `exit code ${r.exitCode}`]; const untracked = await gitUntrackedMarkers(root, runner, policy.timeoutMs, policy.maxEvidenceBytes, options.signal); const evidence = [r.stdout, untracked.text].filter(Boolean).join("\n"); return [r.stdout ? "failed" : untracked.truncated ? "unavailable" : untracked.text ? "failed" : "passed", `${evidence || "none"}${untracked.truncated ? "\nscan incomplete: conflict state unknown" : ""}`]; });
  for (const file of policy.requiredFiles) await add(`required-file:${file}`, `Required file: ${file}`, async () => { const candidate = path.resolve(root, file); let target: string; try { target = await fs.realpath(candidate); } catch (e) { if ((e as NodeJS.ErrnoException).code === "ENOENT") return ["failed", "missing"]; throw e; } const rel = path.relative(root, target); if (rel.startsWith(`..${path.sep}`) || path.isAbsolute(rel)) return ["error", "path escapes workspace"]; if (!(await fs.stat(target)).isFile()) return ["failed", "not a regular file"]; return ["passed", "present"]; });
  for (const c of policy.commands) await add(c.id, c.title, async () => { if (options.signal?.aborted) throw Object.assign(new Error("aborted"), { kind: "cancelled" }); const r = await runner(c.executable, c.args, { cwd: root, timeoutMs: c.timeoutMs ?? policy.timeoutMs, maxBytes: PROCESS_OUTPUT_BYTES, signal: options.signal, env: sanitizedGitEnv() }); return [r.exitCode === 0 ? "passed" : "failed", `${r.stdout}${r.stderr}${r.kind === "partial" ? "\noutput truncated: partial evidence" : ""}` || `exit code ${r.exitCode}`]; }, c.maxEvidenceBytes ?? policy.maxEvidenceBytes);
  if (options.signal?.aborted) { const cancelled = makeResult("run", "Ship Gate run", "skipped", "cancelled", Date.now(), at, policy.maxEvidenceBytes, "cancelled", "cancelled"); const frozenCancelled = [...results, cancelled].map((r) => Object.freeze(r)); return Object.freeze({ workspace: root, collectedAt: at, results: Object.freeze(frozenCancelled), generatedText: "Ship Gate run cancelled", generatedTextTruncated: false }); }
  const frozen = results.map((r) => Object.freeze(r)); const rawText = [`Ship Gate: ${root}`, `Collected: ${at}`, ...frozen.map((r) => `${r.status.toUpperCase()} ${r.title} (${r.durationMs}ms)\n${r.evidence}`)].join("\n\n"); const text = bounded(rawText, policy.maxEvidenceBytes); return Object.freeze({ workspace: root, collectedAt: at, results: Object.freeze(frozen), generatedText: text, generatedTextTruncated: Buffer.byteLength(rawText, "utf8") > policy.maxEvidenceBytes });
}
